variable "environment" {}
variable "project_name" {}
variable "ami" {}
variable "instance_type" {}
variable "common_tags" {}
variable "key_name" {}
variable "subnet_id" {}
variable "instance_name" {}
variable "vpc_security_group_ids" {}